# Numpy

* ## one of the package
* ## arrays handled by numpy
* ## it is the library which we used to handle data analysis,datascience,genai,computer vision project to handle nd array
* ## which handles multidimentional array 1d,2d,nd array
* ## In anaconda it comes by default.If working with VS code then we need to install seperately

# Uses of Numpy
* ## arithetic operations
* ## statistical operations
* ## bitwise
* ## copying and viewing an array
* ## stacking
* ## matrix operations
* ## linear algebra
* ## broadcasting
* ## math operations
* ## searching,sorting,counting

# Array vs Vector
* ## array is horizonal
* ## vector is vertical

In [19]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [20]:
import numpy as np

In [21]:
np.__version__


'2.1.3'

In [22]:
# Creating LIST
my_list=[1,2,3,4]
my_list

[1, 2, 3, 4]

In [23]:
type(my_list)

list

In [24]:
arr=np.array(my_list)
arr

array([1, 2, 3, 4])

In [25]:
type(arr)

numpy.ndarray

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [29]:
np.arange(3.5)

array([0., 1., 2., 3.])

In [31]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
np.arange(20,10) #The first arg should be less than second arg always 

array([], dtype=int64)

In [34]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [35]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [36]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [37]:
np.arange()


TypeError: arange() requires stop to be specified.

In [38]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [39]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.zeros(3)

array([0., 0., 0.])

In [42]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [44]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [45]:
zero=np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [46]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [49]:
np.ones(3)

array([1., 1., 1.])

In [50]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [51]:
np.two(2,3)

AttributeError: module 'numpy' has no attribute 'two'

In [52]:
np.three(3)

AttributeError: module 'numpy' has no attribute 'three'

In [53]:
rand(3,2)

NameError: name 'rand' is not defined

In [54]:
random.rand(3,2)

NameError: name 'random' is not defined

In [55]:
np.random.rand(3) #np is the package,random is the module and rand is the function

array([0.81783708, 0.18695547, 0.36728704])

In [56]:
np.random.rand(5)

array([0.01885955, 0.56652673, 0.43925353, 0.50568804, 0.37369624])

In [58]:
np.random.rand(3,5)

array([[0.9459054 , 0.66182125, 0.24478835, 0.6683099 , 0.08098197],
       [0.1670935 , 0.39720219, 0.69586044, 0.51253244, 0.6214764 ],
       [0.9308836 , 0.72554295, 0.26873152, 0.82003152, 0.35659441]])

In [60]:
np.random.randint(4,6)

5

In [61]:
np.random.randint(0,9,4)

array([0, 2, 5, 6], dtype=int32)

In [62]:
np.random.randint(30,20,10)

ValueError: low >= high

In [63]:
np.random.randint(-30,20,10)

array([ -4,  -7,  -5,  -4,  -8, -20, -23, -25,  -1,   0], dtype=int32)

In [64]:
np.random.randint(10,40,(10,10))

array([[22, 27, 31, 25, 26, 24, 23, 39, 34, 11],
       [18, 29, 21, 20, 18, 30, 24, 39, 22, 18],
       [33, 27, 15, 22, 18, 17, 15, 19, 27, 26],
       [33, 36, 13, 36, 35, 28, 33, 20, 33, 33],
       [16, 18, 34, 17, 29, 21, 24, 23, 26, 21],
       [27, 23, 11, 19, 14, 16, 29, 27, 18, 32],
       [32, 26, 34, 38, 16, 11, 25, 26, 33, 25],
       [29, 24, 10, 36, 32, 26, 12, 39, 31, 10],
       [28, 21, 30, 16, 31, 16, 18, 19, 15, 38],
       [26, 11, 33, 22, 10, 31, 29, 21, 34, 27]], dtype=int32)

In [65]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
np.arange(1,13).reshape(3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [68]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Slicing in Matrix

In [69]:
b=np.random.randint(10,40,(5,4))
b

array([[27, 27, 18, 38],
       [36, 31, 19, 14],
       [21, 24, 14, 30],
       [22, 14, 18, 18],
       [10, 23, 32, 21]], dtype=int32)

In [70]:
b[:]

array([[27, 27, 18, 38],
       [36, 31, 19, 14],
       [21, 24, 14, 30],
       [22, 14, 18, 18],
       [10, 23, 32, 21]], dtype=int32)

In [71]:
b[0]

array([27, 27, 18, 38], dtype=int32)

In [72]:
b[4]

array([10, 23, 32, 21], dtype=int32)

In [73]:
b[-4]

array([36, 31, 19, 14], dtype=int32)