# Slicing

In [75]:
b=np.random.randint(10,20,(5,4))
b

array([[17, 15, 11, 11],
       [18, 11, 11, 11],
       [13, 16, 14, 15],
       [14, 17, 14, 14],
       [17, 12, 13, 13]], dtype=int32)

In [76]:
b[1:3]

array([[18, 11, 11, 11],
       [13, 16, 14, 15]], dtype=int32)

In [77]:
b[1,3]

np.int32(11)

## : will parse row or column
## , gives the specific output

# Numpy Operations

In [78]:
a=np.random.randint(10,20,10)

In [79]:
a

array([12, 10, 17, 14, 15, 17, 13, 16, 15, 19], dtype=int32)

In [80]:
arr2=np.random.randint(90,100,(10,10))

In [81]:
arr2

array([[99, 99, 98, 99, 91, 97, 95, 97, 91, 91],
       [94, 96, 90, 90, 92, 93, 92, 95, 94, 97],
       [99, 99, 92, 92, 92, 95, 98, 96, 91, 95],
       [90, 91, 94, 99, 98, 96, 99, 92, 91, 94],
       [91, 91, 90, 97, 90, 90, 90, 99, 99, 91],
       [96, 97, 96, 93, 95, 94, 90, 98, 95, 97],
       [91, 90, 95, 96, 98, 99, 99, 94, 96, 91],
       [99, 95, 99, 96, 93, 97, 96, 98, 98, 99],
       [99, 95, 93, 96, 96, 91, 94, 90, 97, 94],
       [98, 94, 90, 95, 95, 97, 94, 93, 98, 98]], dtype=int32)

In [83]:
a[:4]

array([12, 10, 17, 14], dtype=int32)

In [85]:
arr2.max()

np.int32(99)

In [86]:
arr2.min()

np.int32(90)

In [87]:
arr2.mean()

np.float64(94.78)

In [88]:
arr2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [91]:
from numpy import *

In [93]:
np.median(arr2)

np.float64(95.0)

In [98]:
# call/print row in a matrix
arr2[2]

array([99, 99, 92, 92, 92, 95, 98, 96, 91, 95], dtype=int32)

In [99]:
#call/print column in a matrix
arr2[:,6]

array([95, 92, 98, 99, 90, 90, 99, 96, 94, 94], dtype=int32)

In [100]:
arr2[:,-1]

array([91, 97, 95, 94, 91, 97, 91, 99, 94, 98], dtype=int32)

In [101]:
arr2[2:6,2:4]

array([[92, 92],
       [94, 99],
       [90, 97],
       [96, 93]], dtype=int32)

# Masking

In [102]:
arr2[arr2>50]

array([99, 99, 98, 99, 91, 97, 95, 97, 91, 91, 94, 96, 90, 90, 92, 93, 92,
       95, 94, 97, 99, 99, 92, 92, 92, 95, 98, 96, 91, 95, 90, 91, 94, 99,
       98, 96, 99, 92, 91, 94, 91, 91, 90, 97, 90, 90, 90, 99, 99, 91, 96,
       97, 96, 93, 95, 94, 90, 98, 95, 97, 91, 90, 95, 96, 98, 99, 99, 94,
       96, 91, 99, 95, 99, 96, 93, 97, 96, 98, 98, 99, 99, 95, 93, 96, 96,
       91, 94, 90, 97, 94, 98, 94, 90, 95, 95, 97, 94, 93, 98, 98],
      dtype=int32)

In [103]:
arr2[arr2>=50]

array([99, 99, 98, 99, 91, 97, 95, 97, 91, 91, 94, 96, 90, 90, 92, 93, 92,
       95, 94, 97, 99, 99, 92, 92, 92, 95, 98, 96, 91, 95, 90, 91, 94, 99,
       98, 96, 99, 92, 91, 94, 91, 91, 90, 97, 90, 90, 90, 99, 99, 91, 96,
       97, 96, 93, 95, 94, 90, 98, 95, 97, 91, 90, 95, 96, 98, 99, 99, 94,
       96, 91, 99, 95, 99, 96, 93, 97, 96, 98, 98, 99, 99, 95, 93, 96, 96,
       91, 94, 90, 97, 94, 98, 94, 90, 95, 95, 97, 94, 93, 98, 98],
      dtype=int32)

In [104]:
arr2[arr2<50]

array([], dtype=int32)

In [105]:
arr2[arr2==50]

array([], dtype=int32)

In [106]:
arr2[arr2!=50]

array([99, 99, 98, 99, 91, 97, 95, 97, 91, 91, 94, 96, 90, 90, 92, 93, 92,
       95, 94, 97, 99, 99, 92, 92, 92, 95, 98, 96, 91, 95, 90, 91, 94, 99,
       98, 96, 99, 92, 91, 94, 91, 91, 90, 97, 90, 90, 90, 99, 99, 91, 96,
       97, 96, 93, 95, 94, 90, 98, 95, 97, 91, 90, 95, 96, 98, 99, 99, 94,
       96, 91, 99, 95, 99, 96, 93, 97, 96, 98, 98, 99, 99, 95, 93, 96, 96,
       91, 94, 90, 97, 94, 98, 94, 90, 95, 95, 97, 94, 93, 98, 98],
      dtype=int32)