In [3]:
import numpy as np

# 1.Array Creation Function

In [8]:
# create an array from list
a=np.array([1,2,3])
print("Array a:\n",a)

Array a:
 [1 2 3]


In [5]:
# create an array filled with zeros
d=np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# create an array fileed with ones
e=np.ones((3,2))
print("Array e\n",e)

Array e
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# create an identity matrix
f=np.eye(4)
print("Identity matrix f:\n",f)

# Array Manipulations

In [12]:
#Reshape an array
a1=np.array([1,2,3])
reshape=np.reshape(a1,(1,3))
print("Reshaped array:",reshape)

Reshaped array: [[1 2 3]]


In [13]:
#Reshape an array
a1=np.array([1,2,3])
reshape=np.reshape(a1,(3,1))
print("Reshaped array:",reshape)

Reshaped array: [[1]
 [2]
 [3]]


In [14]:
#Flatten an array
f1=np.array([[1,2],[3,4]])
flattened=np.ravel(f1)
print("flattened array",flattened)

flattened array [1 2 3 4]


In [15]:
#Transpose an array
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1)
print("Transposed array\n",transposed)

Transposed array
 [[1 3]
 [2 4]]


In [17]:
# Stack arrays vertically
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2]) # stack a2 and b2 vertically
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [[1 2]
 [3 4]]
